const { differenceInDays, parseISO, isValid } = require('date-fns')

/**
 * Calculates the percentage of time consumed between two dates.
 * @param {string} startStr - Start date in YYYY-MM-DD format
 * @param {string} endStr - End date in YYYY-MM-DD format
 * @returns {object} An object containing the percentage integer and a status flag
 */
function calculateProgress(startStr, endStr) {
  // 1. Parse strings into actual Date objects
  const startDate = parseISO(startStr)
  const endDate = parseISO(endStr)
  const currentDate = new Date() // Today's date

  // 2. Validation: Ensure the dates are structurally valid
  if (!isValid(startDate) || !isValid(endDate)) {
    return {
      success: false,
      percentage: 0,
      error: 'Invalid date formats provided.',
    }
  }

  // 3. Validation: Ensure the timeline makes chronological sense
  if (differenceInDays(endDate, startDate) <= 0) {
    return {
      success: false,
      percentage: 0,
      error: 'End date must be after start date.',
    }
  }

  // 4. Edge Case: If today hasn't reached the start date yet
  if (differenceInDays(startDate, currentDate) > 0) {
    return { success: true, percentage: 0, status: 'upcoming' }
  }

  // 5. Edge Case: If today has surpassed the deadline
  if (differenceInDays(currentDate, endDate) > 0) {
    return { success: true, percentage: 100, status: 'completed' }
  }

  // 6. Core Math Formula
  const totalDays = differenceInDays(endDate, startDate)
  const daysPassed = differenceInDays(currentDate, startDate)

  // Calculate percentage and round it to the nearest whole number
  const percentage = Math.round((daysPassed / totalDays) * 100)

  return { success: true, percentage: percentage, status: 'active' }
}

// Export the function so index.js can use it later
module.exports = { calculateProgress }

const MOTIVATIONAL_QUOTES = [
  "Don't stop when you're tired. Stop when you're done.",
  'Every strike brings me closer to the next home run.',
  "Hard work beats talent when talent doesn't work hard.",
  'The only way to do great work is to love what you do.',
  'Precision beats power, and timing beats speed.',
  'Remember why you started. Push harder today!',
  'Small daily improvements over time lead to stunning results.',
  'Your future self is counting on you to outwork your doubts today.',
  'Success is built one disciplined day at a time.',
  'Consistency turns ordinary effort into extraordinary results.',
  'The work you avoid today becomes the obstacle you face tomorrow.',
  'Focus on progress, not perfection.',
  'Every challenge is training for a stronger version of you.',
  'Discipline creates opportunities that motivation cannot sustain.',
  'Great achievements begin with small actions repeated daily.',
  'Keep showing up even when the results are invisible.',
  'Your habits are writing the story of your future.',
  'Growth starts where comfort ends.',
  'Discipline is choosing what you want most over what you want now.',
  'Small habits, repeated daily, become the architecture of a life.',
  'Motivation gets you started; discipline keeps you going.',
  'What you do every day matters more than what you do once in a while.',
  'Discipline is the bridge between goals and accomplishment.',
  'The habits you build in silence are the ones that define you in public.',
  'A disciplined morning often predicts a productive day.',
  "You don't need more time, you need more discipline with the time you have.",
  'Routines free your mind so your willpower can focus on what matters.',
  'Excellence is not an accident; it is a habit practiced on purpose.',
  'The difference between who you are and who you want to be is what you do today.',
  'Self-control today is freedom tomorrow.',
  'A single rep, a single page, a single step, repeated, becomes mastery.',
  "Discipline doesn't feel like much in the moment, but it compounds like interest.",
  "You can't out-talent a lack of discipline forever.",
  "Show up even when no one is watching; that's where character is built.",
  'Good habits are hard to start but easy to live with; bad habits are the opposite.',
  'The boring, consistent path is usually the fastest one.',
  'Discipline is remembering what you want most, not what you feel right now.',
  "Every disciplined choice today is a vote for the person you're becoming.",
  'Effort is the one variable in life you almost always control.',
  "Hard work doesn't guarantee success, but it guarantees you won't lose to someone who tried less.",
  "Sweat now so you don't have to apologize later.",
  'The harder the climb, the better the view from the top.',
  'Talent opens the door; effort decides how far you walk through it.',
  'Work like the results depend entirely on you, because mostly, they do.',
  'Nothing replaces the value of simply putting in the hours.',
  'The grind is invisible, but the results are not.',
  "Outwork your doubts; they're loudest when you're standing still.",
  'There is no shortcut that beats showing up and doing the work.',
  "Effort compounds quietly until one day it's undeniable.",
  'The price of mastery is paid in unglamorous repetition.',
  'Hard work is a conversation between you and your future.',
  'You earn confidence the same way you earn calluses: through repetition.',
  'Some days effort feels invisible. Trust it anyway.',
  "The work you do when it's hard is the work that actually counts.",
  'Strength is built in the rounds you wanted to quit.',
  'A strong work ethic is the quiet kind of talent.',
  'Done with effort beats perfect with excuses.',
  'Put in the work today that your future self will thank you for.',
  "You don't have to be great to start, but you have to start to be great.",
  'Growth lives just outside your comfort zone, never inside it.',
  'Every version of you was once a beginner at something.',
  'Progress is rarely loud; it just quietly adds up.',
  'Comparison steals joy; growth only asks you to beat yesterday.',
  "The goal isn't perfection, it's becoming a little better than you were.",
  "You're not behind, you're exactly where your effort has placed you, and that can change.",
  'Improvement is a direction, not a destination.',
  "Stretch yourself today so tomorrow's challenges feel smaller.",
  'The student who keeps asking questions eventually becomes the expert.',
  "Every skill you have now was once something you couldn't do.",
  'Growth asks for patience first and talent second.',
  'You grow the most in the moments you wanted to give up.',
  "Today's discomfort is tomorrow's competence.",
  'The only competition that matters is the one with who you were yesterday.',
  'Small upgrades, repeated often, eventually look like transformation.',
  'Avoiding mistakes also means avoiding growth.',
  "You can't improve what you refuse to examine honestly.",
  'Real growth often looks like failure from the outside.',
  'Choose progress over comfort, every single time you can.',
  'Failure is feedback, not a final verdict.',
  "Fall seven times, stand up an eighth; that's the whole game.",
  'Setbacks are detours, not dead ends.',
  'The comeback is always stronger than the setback that caused it.',
  "You haven't failed until you stop trying.",
  'Every successful person has a graveyard of failed attempts behind them.',
  "Resilience isn't about never breaking, it's about learning to rebuild.",
  'Bend before you break, then straighten back up.',
  'Pain is temporary, quitting lasts forever.',
  'The bravest thing you can do after falling is try again.',
  "Strength isn't tested in comfort, it's revealed in collapse and recovery.",
  'Every closed door is redirection, not rejection.',
  "You're allowed to fall apart, just don't forget to rebuild.",
  'The wound is where the lesson lives.',
  "Storms don't last, but the skills you build surviving them do.",
  'What breaks you today can build you tomorrow, if you let it.',
  'Resilience is just patience with extra grit.',
  "You don't need to win every round to win the fight.",
  'Hard seasons grow the deepest roots.',
  'The setback is only permanent if you decide it is.',
  'Where attention goes, energy flows, and results follow.',
  'A scattered mind builds nothing; a focused one builds everything.',
  'Say no to the noise so you can say yes to the goal.',
  "Determination doesn't ask for motivation's permission.",
  'One clear target beats ten blurry ones.',
  'The world will hand you distractions; you have to choose focus instead.',
  'Tunnel vision, when aimed at the right goal, is a superpower.',
  'Single-mindedness is underrated in a world built to scatter you.',
  'Decide what matters, then guard it fiercely.',
  'Focus is simply deciding what to ignore.',
  'A determined mind finds a way; an undecided one finds an excuse.',
  'Energy follows intention, not the other way around.',
  'Stay locked on the target even when the path bends.',
  'Distraction is the enemy that wears a friendly face.',
  'The undistracted mind moves faster than the talented one.',
  'Determination is quiet, but it outlasts loud doubt.',
  'Keep your eyes on the goal, not on the noise around it.',
  'Discipline your attention and your results will follow.',
  'Clarity of purpose cuts through any amount of confusion.',
  'Stay so focused on your lane that comparison loses its grip.',
  "Courage isn't the absence of fear, it's moving forward despite it.",
  "Do the thing that scares you; that's usually the thing that grows you.",
  "Fear is a terrible navigator but an honest signal that you're growing.",
  'The bravest step is often the smallest one taken today.',
  "You don't need to feel fearless to act with courage.",
  'Most fear evaporates the moment you take action against it.',
  'Bravery is a habit built one uncomfortable choice at a time.',
  'What you fear most often guards the growth you need most.',
  'Step toward the fear; it shrinks every time you do.',
  'Courage rarely roars; mostly it just quietly tries again tomorrow.',
  'You can be scared and still be unstoppable.',
  'Fear shrinks the moment you stop feeding it with hesitation.',
  'The boldest move is rarely the loudest one.',
  'Act first, let confidence catch up later.',
  'Anxiety whispers "stop"; courage whispers "one more step."',
  'On the other side of fear is almost always relief.',
  "The things you're avoiding are usually the things worth doing.",
  "Brave doesn't mean unafraid, it means willing anyway.",
  "Every comfort zone has an exit, and it's called courage.",
  'Fear and excitement often feel the same; choose how you label it.',
  'A goal without a deadline is just a wish in disguise.',
  'Dream loudly, but work quietly.',
  'Write the goal down; vague hopes rarely build anything real.',
  'Big dreams need small, boring daily actions to survive.',
  "Your goals don't care how you feel today, only what you do.",
  'Chase the goal, not the applause that might come with it.',
  'A clear goal turns chaos into a checklist.',
  "The size of your goal should scare you a little; that means it's worth chasing.",
  'Set the goal, then build the habit that gets you there.',
  "Don't just dream about it, schedule it.",
  'Dreams without deadlines are just decorations for your mind.',
  'Your future is built by the goals you protect today.',
  'A goal you whisper to yourself is still a goal worth fighting for.',
  'Make the goal specific enough that excuses have nowhere to hide.',
  'The gap between dreaming and doing is called discipline.',
  'Big goals are just a series of small wins stacked high.',
  "Plant the goal today, water it daily, and don't dig it up to check.",
  "You don't need permission to dream bigger than your circumstances.",
  'A goal becomes real the day you start treating it like a plan.',
  'Revisit your goal often enough that you never forget why you started.',
  'The best time to start was earlier; the next best time is now.',
  "Time doesn't wait for confidence to arrive.",
  "Every minute spent waiting is a minute you can't get back.",
  'Action cures hesitation faster than thinking ever will.',
  "Don't wait for the perfect moment, build it with the time you have.",
  "The clock doesn't care about your excuses, only your choices.",
  'You will never feel fully ready; start before you do.',
  'One honest hour of action beats a week of overthinking.',
  'Time spent planning forever is time stolen from doing.',
  "The minutes you waste today are borrowed from tomorrow's progress.",
  "Today's small action is worth more than tomorrow's perfect plan.",
  'Move now; momentum is easier to keep than to create.',
  "There's no dress rehearsal for your life, so act like it counts.",
  'Stop waiting for motivation; let action manufacture it instead.',
  "A year from now you'll wish you had started today.",
  "Time is the only resource you can't refund, spend it on purpose.",
  'The first step rarely feels significant, but it always is.',
  'Procrastination is just fear wearing the disguise of "later."',
  "Use today like it's the only guarantee you actually have.",
  "Don't count the days, make the days count.",
  'Your mindset is the lens that decides how hard the climb feels.',
  "Believe you can, and you've already won half the battle.",
  'The mind that expects obstacles handles them better than the one that denies them.',
  'Change your story about yourself and your results often follow.',
  "A flexible mindset survives storms a rigid one can't.",
  'You become what you repeatedly tell yourself you are.',
  'The voice in your head needs better material; feed it on purpose.',
  "Optimism isn't naive, it's a strategy for staying in the game.",
  'Your thoughts are the architects quietly designing your habits.',
  'A growth mindset turns every failure into a lesson plan.',
  'Doubt is just a thought, not a fact, unless you obey it.',
  'What you believe about yourself sets the ceiling on what you attempt.',
  'The mind is a garden; what you plant in it eventually grows.',
  'Train your thoughts the same way you train your muscles, deliberately.',
  "Confidence is just a belief you've practiced enough times to trust.",
  'Negative self-talk is a habit, which means it can be unlearned.',
  'The story you tell yourself about today shapes what tomorrow looks like.',
  'A calm mind makes better decisions than a panicked one.',
  "Your attitude is the one variable that's always within reach.",
  "Believe in the process even on days the results don't show up yet.",
  "Consistency is choosing to show up on the days you don't feel like it.",
  "Patience isn't passive, it's actively trusting the process.",
  'Slow progress is still progress, and it compounds.',
  "The tortoise didn't win by being fast, it won by never stopping.",
  "Trust the boring middle; that's where most of the work happens.",
  'Consistency turns talent into mastery over time.',
  "Rome wasn't built in a day, but they were laying bricks every day.",
  'The seeds you plant today rarely bloom on the same afternoon.',
  'Patience is the quiet partner of every long-term success story.',
  'Small, steady steps outpace dramatic, inconsistent leaps.',
  "Don't measure your progress hourly; measure it in seasons.",
  "The magic is rarely in the breakthrough, it's in the repetition before it.",
  "Stay consistent even when the results feel invisible; they're compounding quietly.",
  'Patience turns effort into mastery, given enough time.',
  'A little progress each day adds up to big results.',
  'The difference between ordinary and extraordinary is often just persistence.',
  'Trust the slow build; instant results rarely last anyway.',
  "Plant now, even if you won't see the harvest for a while.",
  'Consistency is a love letter you write to your future self.',
  'What feels repetitive today is what feels like mastery tomorrow.',
  "Character is what you do when applause isn't part of the deal.",
  "Lead by example; it's the only kind of leadership people actually follow.",
  'Integrity means your private choices match your public claims.',
  'A good leader makes the people around them better, not smaller.',
  'Your reputation is built in moments no one is recording.',
  "Real influence is earned in private, long before it's noticed in public.",
  "Leadership isn't a title, it's a pattern of choices made for others.",
  'The strongest leaders listen more than they speak.',
  'Character is consistency between your values and your actions.',
  'Trust is built slowly and lost quickly, treat it carefully.',
  'A true leader takes the blame and shares the credit.',
  'Your word means more than your résumé ever will.',
  'Lead with humility; arrogance is a slow leak in any team.',
  "The way you treat people when nothing's at stake reveals everything.",
  'Service is the quietest, most powerful form of leadership.',
  "Be the kind of person you'd want leading you.",
  "Accountability is leadership's unglamorous, essential ingredient.",
  'Strong leaders build other leaders, not just followers.',
  'Honesty under pressure is where character actually gets tested.',
  'People remember how you made them feel long after they forget what you said.',
  'Gratitude turns ordinary days into ones worth remembering.',
  'Find one thing to appreciate today; it changes the whole lens.',
  'A grateful mind has less room left for anxiety.',
  "Celebrate the small wins, they're the bricks of every big one.",
  "Positivity isn't pretending it's fine, it's choosing to keep going anyway.",
  "Notice what's working before you fix what isn't.",
  'Appreciation is free, and it multiplies whatever you give it to.',
  'A thankful heart finds reasons to smile in ordinary moments.',
  'Gratitude is the quiet fuel behind sustainable motivation.',
  "The more you notice what's good, the more good you tend to notice.",
  'Today is someone else\'s "I wish I had that," don\'t waste it.',
  'Optimism is a discipline disguised as a personality trait.',
  'Joy multiplies the moment you decide to share it.',
  'Even hard days carry something worth being grateful for.',
  "A positive outlook doesn't ignore reality, it just refuses to be ruled by it.",
  "Count what you have, not what you're missing.",
  "Gratitude shifts focus from what's lacking to what's already enough.",
  'Smile first; the mood usually follows.',
  "The little things are only little until you're grateful for them.",
  'A thankful mindset turns pressure into perspective.',
  'The one constant in life is change, so make peace with it early.',
  "Flexibility isn't weakness, it's the strength that survives the storm.",
  "What got you here won't necessarily get you there; be willing to adapt.",
  "Bend with the wind or you'll eventually break against it.",
  'Change is uncomfortable right up until it becomes your new normal.',
  'The fastest way to fall behind is refusing to evolve.',
  'Adaptability is the quiet skill behind every long-lasting success.',
  'Comfort with change is a competitive advantage few people develop.',
  'Old habits die hard, but new ones can be built deliberately.',
  'The world rewards those who pivot quickly, not those who resist forever.',
  'Growth often demands letting go of what used to work.',
  'Stay curious about change instead of afraid of it.',
  'Some doors close so better ones can open.',
  'Adjust the plan, not the goal.',
  'The willingness to change is often the only thing standing between you and progress.',
  'Adapt like water; find a way around every obstacle.',
  "Change reveals who's actually flexible and who was only pretending to be.",
  'You can resist change or you can learn from it; only one of those moves you forward.',
  'Every new season asks for a slightly updated version of you.',
  'Stagnation is the real risk, not change.',
  'Willpower is a muscle, train it daily and it grows stronger.',
  'Discipline is doing what needs to be done, even without feeling like it.',
  'Self-control today builds the freedom you want tomorrow.',
  "The strongest people aren't immune to temptation, they've just practiced resisting it more.",
  'Will power fades by evening, so do the hard things first.',
  'The space between impulse and action is where self-discipline lives.',
  'Master your urges before they master your outcomes.',
  'Saying no to distractions is saying yes to your goals.',
  'Strength of will shows up most in the boring, unglamorous moments.',
  "You don't need more willpower, you need fewer decisions draining it.",
  'Discipline whispers "you\'ll thank me later."',
  "Restraint today is investment in who you're becoming.",
  "The disciplined mind doesn't negotiate with excuses.",
  "Build systems so willpower isn't the only thing holding the line.",
  'Every small act of self-control compounds into self-respect.',
  "Discipline isn't punishment, it's self-respect in action.",
  'The harder choice usually leads to the better outcome.',
  "Will is strongest right after you've practiced using it.",
  "Choose the version of yourself you'll respect tomorrow morning.",
  "The mind obeys the habits you've trained it to follow.",
  "Success is rarely an accident, it's a pattern repeated on purpose.",
  "Define success on your own terms before chasing someone else's version.",
  'Achievement is the visible tip of an invisible iceberg of effort.',
  'Real success feels earned, not given.',
  'Success often shows up disguised as relentless ordinary effort.',
  "The summit looks impossible until you're standing on top of it.",
  'Achievement compounds quietly, then arrives all at once.',
  "Success isn't a single finish line, it's a series of decisions repeated.",
  'Most overnight successes took years of unseen mornings.',
  'Winning is mostly about not quitting before the turning point arrives.',
  'Success rewards the version of you that kept showing up after losing interest.',
  "Your definition of success should outlast other people's opinions.",
  'Achievement is just discipline wearing a celebratory outfit.',
  'The climb matters more than the view, even if the view gets the credit.',
  'Success is built in private and revealed in public.',
  'Every achievement has an unglamorous backstory of repetition.',
  "You don't need luck if you're consistent enough, long enough.",
  "Real success leaves room for other people's success too.",
  'Measure success by growth, not just outcome.',
  'The proudest wins are usually the ones that demanded the most patience.',
  'Stay curious longer than you stay comfortable.',
  'The day you stop learning is the day you stop growing.',
  "Ask better questions and you'll find better answers.",
  "Curiosity is the engine behind every meaningful skill you've ever built.",
  'Read like your future depends on it, because in some ways, it does.',
  "The beginner's mind sees opportunities the expert's mind has stopped noticing.",
  'Every mistake is tuition paid toward future mastery.',
  'Stay a student of your craft long after you become good at it.',
  'Knowledge without action is just trivia; apply what you learn.',
  'The most successful people are usually the most relentless learners.',
  "Don't fear looking foolish while learning; fear staying stagnant instead.",
  'Curiosity turns ordinary days into unexpected classrooms.',
  'Learning compounds faster than almost anything else you can invest in.',
  'Stay teachable; arrogance is where growth quietly stops.',
  'The questions you ask shape the future you build.',
  'Every expert was once a beginner who refused to quit early.',
  "Growth requires admitting you don't know everything yet.",
  'A curious mind rarely stays bored for long.',
  'Skills compound; the second one you learn is always easier than the first.',
  'Treat every setback as a lesson, not a verdict.',
  'Confidence is built in the gym of small, repeated wins.',
  "You don't need permission to believe in yourself.",
  "Self-worth shouldn't fluctuate with someone else's opinion of you.",
  "Speak to yourself the way you'd speak to someone you love.",
  "Confidence isn't arrogance, it's calm trust in your own preparation.",
  'You are allowed to take up space and chase big things.',
  "Stop auditioning for approval you don't actually need.",
  'The right people will never require you to shrink yourself.',
  'Self-respect is the quiet foundation under every lasting success.',
  'You are not behind; you are exactly on your own timeline.',
  "Confidence grows the moment you stop comparing your chapter one to someone's chapter twenty.",
  'Believe in your own potential before the evidence fully arrives.',
  "Worth isn't earned through performance, it's already yours.",
  'Walk like you already know your value, because you do.',
  'The bravest form of confidence is trusting yourself in uncertainty.',
  "Your past mistakes don't get a vote in your future.",
  'Stand tall in your story, even the messy chapters.',
  'Confidence is quiet practice, not loud performance.',
  "You don't need to be the loudest in the room to be the most certain.",
  'Trust the version of yourself that kept going when it was hard.',
  'Grit is choosing to finish what motivation only started.',
  'Keep going, especially on the days no one is clapping.',
  'Perseverance turns ordinary people into extraordinary stories.',
  'The finish line rewards those who refused to stop walking toward it.',
  "Endurance isn't glamorous, but it's almost always decisive.",
  'Some days all you can do is the next small step, so take it.',
  'Grit is staying in the fight after the excitement has worn off.',
  'Quitting is loud in the moment and quiet in regret forever.',
  'The ones who make it usually just refused to stop trying.',
  'Every long journey is just a series of "one more steps."',
  'Perseverance is patience that refuses to give up.',
  "Push through the middle; that's where most people quit.",
  "The struggle you're in today is shaping the strength you'll need tomorrow.",
  'Stay in the race even when your pace slows, finishing matters more than speed.',
  'Grit shows up loudest in the quietest, hardest moments.',
  'Keep your commitment even after your motivation has left the building.',
  'The difference between dreamers and achievers is usually just persistence.',
  'Hold the line a little longer than feels comfortable.',
  'Endurance is built one uncomfortable round at a time.',
  "You're closer to the breakthrough than the exhaustion makes it feel.",
  'A clear purpose makes hard work feel lighter.',
  'Know your "why" and the "how" becomes easier to find.',
  'Vision turns an ordinary Tuesday into a meaningful step forward.',
  'Purpose is the compass that keeps effort pointed somewhere worthwhile.',
  'Without a clear vision, even hard work can feel directionless.',
  'Define what matters to you before letting the world define it for you.',
  'A strong sense of purpose survives even the hardest seasons.',
  "Your purpose doesn't need to be loud to be powerful.",
  'Vision pulls you forward when motivation alone runs dry.',
  'Live with intention, or someone else will hand you their agenda.',
  'Purpose-driven effort rarely feels like a waste of time.',
  'The clearer your "why," the easier the "no" becomes to distractions.',
  'A meaningful goal makes the sacrifice along the way worth it.',
  'Build a life aligned with your values, not just your habits.',
  'Purpose is the fuel that outlasts fleeting motivation.',
  "Know what you're building toward, even on the days you can't see it.",
  'Vision turns scattered effort into a focused direction.',
  'The "why" behind your work decides how far you\'ll carry it.',
  'A life without purpose drifts; a life with it moves forward.',
  'Let your purpose be bigger than your present circumstances.',
  'Motivation gets you to start, momentum keeps you moving, discipline finishes the job.',
  "You don't always need motivation, sometimes you just need to begin.",
  'Energy follows action more often than action follows energy.',
  'A little momentum today saves a lot of motivation tomorrow.',
  'Show up tired; the energy often arrives after you start.',
  'Motivation is a spark, but habit is the fire that lasts.',
  'The energy you bring to the morning shapes the rest of the day.',
  "Don't wait to feel inspired, act your way into inspiration instead.",
  "Your energy is contagious, choose what you're spreading carefully.",
  "Motivation fades fast, build systems that don't depend on it.",
  'A burst of energy today can carry momentum into tomorrow.',
  'Protect your energy the same way you protect your time.',
  'The first step often creates the motivation the next step needs.',
  'Stay energized by remembering why you started this in the first place.',
  'Momentum is easier to maintain than it is to create from scratch.',
  'Low motivation is normal; showing up anyway is the skill.',
  'The right energy in the room can shift an entire outcome.',
  'Treat motivation like weather, plan your actions around it instead of waiting for it.',
  'Small wins generate the energy that big goals require.',
  'Fuel your momentum with progress, not just hype.',
  'Opportunity rarely waits for you to feel fully ready.',
  'The biggest risk is often staying comfortable for too long.',
  'Bet on yourself before asking anyone else to.',
  'Opportunities multiply for those who are already in motion.',
  'Calculated risks build the stories worth telling later.',
  "Every opportunity carries a little uncertainty, that's the cost of growth.",
  'Hesitation is the quiet thief of opportunity.',
  "The door doesn't open wider just because you waited longer outside it.",
  'Sometimes the safest choice is the riskiest one in disguise.',
  'Take the leap before the doubts finish their meeting.',
  'Opportunity favors the prepared and the willing.',
  'The biggest opportunities rarely come with a guarantee attached.',
  'Risk is just the price tag on meaningful growth.',
  'Say yes to the opportunity, then figure out the "how" along the way.',
  'The cost of inaction is often higher than the cost of trying.',
  'Every "yes" to opportunity is also a "no" to staying the same.',
  'The window of opportunity is usually shorter than it looks.',
  'Bold moves attract opportunities cautious ones never see.',
  'Sometimes you have to risk the comfortable to reach the remarkable.',
  "Opportunities are rarely lost, they're usually just given to someone bolder.",
  'Ambition without collaboration eventually hits a ceiling.',
  'Surround yourself with people whose habits you want to inherit.',
  'Big dreams are easier to carry when shared with the right team.',
  'Ambition fuels the climb, but people make the journey worthwhile.',
  'The right team multiplies what one determined person can do alone.',
  'Lift others as you climb; it makes the summit feel better anyway.',
  'Ambition asks "how far," collaboration asks "how together."',
  'A rising tide is even better when you helped build the wave.',
  'Healthy ambition competes with yesterday, not with the people beside you.',
  'The strongest goals are rarely reached completely alone.',
  'Find people who challenge your comfort zone and celebrate your growth.',
  'Shared ambition multiplies individual effort.',
  "A great team turns one person's vision into everyone's mission.",
  'Ambition is fuel, but humility is what keeps the team running.',
  'Build relationships as deliberately as you build your skills.',
  'Your network is often the quiet multiplier behind your biggest wins.',
  'Generosity and ambition can absolutely coexist.',
  "The best collaborators make your weaknesses someone else's strength.",
  'Big goals get smaller when divided across the right people.',
  'Ambition climbs higher when it brings others along for the ride.',
  'Take care of the body that has to carry your ambitions.',
  'Energy management matters as much as time management.',
  "Rest isn't laziness, it's the maintenance your ambition depends on.",
  'A clear mind needs a rested body to support it.',
  'Movement is medicine for both the body and the mood.',
  "You can't pour from a body you've neglected, refill it on purpose.",
  'Sleep is the quiet foundation under every productive day.',
  'Strength training the body often strengthens the mind right alongside it.',
  'Discipline in your health habits often spills into every other area.',
  'Your energy levels are a daily choice disguised as routine.',
  'Burnout is the cost of ignoring rest for too long.',
  'A short walk can clear a cluttered mind faster than overthinking ever will.',
  'Hydrate, move, breathe, the basics matter more than they get credit for.',
  'The body keeps the score, treat it like it matters.',
  'Mental clarity often starts with physical care.',
  'Protect your sleep the same way you protect your goals.',
  'Strong habits in the body build strong habits in the mind.',
  'Stress shrinks when movement enters the equation.',
  'Recovery is part of the training, not separate from it.',
  'Treat your wellbeing like the long-term investment it actually is.',
  'Creativity rewards the people brave enough to make something imperfect first.',
  'Innovation often starts as a question no one else dared to ask.',
  'The blank page fears the person who simply starts.',
  'Original ideas usually arrive after a lot of ordinary ones.',
  'Creativity thrives on curiosity and dies in comfort.',
  "Don't wait for inspiration, invite it by starting the work.",
  "The first draft's only job is to exist, not to be perfect.",
  'Innovation is just persistence applied to a new problem.',
  'Borrow ideas freely, then make them undeniably your own.',
  'Creative breakthroughs usually hide behind a hundred forgettable attempts.',
  'Constraints often spark more creativity than total freedom does.',
  'The willingness to look silly is often the price of originality.',
  'New ideas need room to be bad before they can become brilliant.',
  'Innovation rewards the curious mind that kept asking "what if."',
  'Creativity is intelligence having fun with a problem.',
  'Make something today, refine it tomorrow; perfection can wait its turn.',
  'The most original ideas often come from connecting unrelated ones.',
  'Stay playful with problems; rigid minds rarely innovate.',
  'Every masterpiece began as a rough, unfinished idea.',
  'Innovation is simply curiosity that refused to stop at the first answer.',
  'Starting is easy, finishing is where character shows up.',
  "The last mile is harder, but it's also where the real growth lives.",
]

/**
 * Grabs a random string from our collection of quotes.
 * @returns {string} A motivational quote
 */
function getRandomQuote() {
  const randomIndex = Math.floor(Math.random() * MOTIVATIONAL_QUOTES.length)
  return MOTIVATIONAL_QUOTES[randomIndex]
}

// Update our exports to include the new function
module.exports = {
  calculateProgress,
  getRandomQuote,
}
